"""An empty actions list means the cleaner left the bytes alone (#173).

Every strip_* used to append a "no X removed" filler when it removed nothing,
so the actions list was never empty for any non-text kind. clean_staged._changed()
reads that list to decide whether a file was modified, which made it
unconditionally True: the clean pre-commit hook exited 1 for every image and
container forever, and its "cleaned N file(s)" line carried no information.
"""

from __future__ import annotations

import shutil
import struct
import sys
import zlib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(SCRIPTS))

import clean_staged
import container_meta
from container_meta import clean_html, clean_markdown, clean_pdf, clean_svg
from image_meta import strip_bmp, strip_jpeg, strip_png


def _png_chunk(ctype: bytes, payload: bytes) -> bytes:
    crc = zlib.crc32(ctype + payload) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


def _minimal_png(*extra: tuple[bytes, bytes]) -> bytes:
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", ihdr)
        + b"".join(_png_chunk(c, p) for c, p in extra)
        + _png_chunk(b"IDAT", zlib.compress(b"\x00\x00\x00\x00"))
        + _png_chunk(b"IEND", b"")
    )


def _minimal_bmp(*, trailing: bytes = b"") -> bytes:
    pixel = b"\x00\x00\xff\x00"
    dib = struct.pack("<IiiHHIIiiII", 40, 1, 1, 1, 24, 0, len(pixel), 2835, 2835, 0, 0)
    header = b"BM" + struct.pack("<IHHI", 14 + len(dib) + len(pixel), 0, 0, 14 + len(dib))
    return header + dib + pixel + trailing


def _minimal_jpeg(*, comment: bytes | None = None) -> bytes:
    out = b"\xff\xd8"
    if comment is not None:
        out += b"\xff\xfe" + struct.pack(">H", len(comment) + 2) + comment
    out += b"\xff\xda" + struct.pack(">H", 12) + b"\x01" * 10 + b"\xff\xd9"
    return out


# --- nothing removed -> no actions -----------------------------------------


def test_clean_png_reports_no_actions():
    data = _minimal_png()
    cleaned, actions = strip_png(data)
    assert cleaned == data
    assert actions == []


def test_clean_jpeg_reports_no_actions():
    data = _minimal_jpeg()
    cleaned, actions = strip_jpeg(data)
    assert cleaned == data
    assert actions == []


def test_clean_markdown_reports_no_actions():
    cleaned, actions = clean_markdown("# Title\n\nOrdinary prose.\n")
    assert actions == []
    assert "Ordinary prose." in cleaned


def test_clean_html_reports_no_actions():
    html = "<html><body><p>hello</p></body></html>"
    cleaned, actions = clean_html(html)
    assert actions == []
    assert cleaned == html


def test_clean_svg_reports_no_actions():
    data = b'<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>'
    cleaned, actions = clean_svg(data)
    assert actions == []
    assert cleaned == data


def test_bmp_keeping_unflagged_trailing_bytes_is_not_an_action():
    """--keep-non-ai-metadata honoured on unmarked trailing bytes is a no-op.

    Nothing was removed and nothing marked was found, so the file is untouched.
    Trailing bytes carrying markers are still dropped even under this flag,
    which is covered by test_bmp_trailing_metadata_detected_and_stripped.
    """
    data = _minimal_bmp(trailing=b"trailing bytes without markers")
    kept, actions = strip_bmp(data, strip_all_metadata=False)
    assert kept == data
    assert actions == []


def test_bmp_marked_trailing_bytes_are_dropped_even_when_keeping(tmp_path):
    """The keep flag must never suppress a real mark."""
    data = _minimal_bmp(trailing=b"<x:xmpmeta>OpenAI</x:xmpmeta>")
    cleaned, actions = strip_bmp(data, strip_all_metadata=False)
    assert cleaned != data
    assert any("drop" in a for a in actions)


# --- a real removal still reports it ---------------------------------------


def test_png_with_ai_text_chunk_still_reports_the_drop():
    data = _minimal_png((b"tEXt", b"Software\x00Midjourney v6"))
    cleaned, actions = strip_png(data)
    assert actions, "a real removal must still produce an action"
    assert cleaned != data


def test_markdown_with_ai_frontmatter_still_reports_the_drop():
    cleaned, actions = clean_markdown("---\ngenerator: ChatGPT\n---\nBody\n")
    assert any("drop" in a for a in actions)
    assert "generator: ChatGPT" not in cleaned


def test_jpeg_preserved_scan_note_only_accompanies_a_removal():
    """The note describes what was carried over, not a change.

    On a no-op clean it must not appear, or it alone would mark the file
    changed. Alongside a real removal it is still worth reporting.
    """
    assert strip_jpeg(_minimal_jpeg())[1] == []
    marked = strip_jpeg(_minimal_jpeg(comment=b"Generated by ChatGPT"))[1]
    assert any("drop" in a for a in marked)
    assert any("preserved entropy-coded scan" in a for a in marked)


# --- the regression that motivated this ------------------------------------


def test_clean_hook_exits_0_for_an_already_clean_image(tmp_path, monkeypatch):
    f = tmp_path / "pic.png"
    f.write_bytes(_minimal_png())
    before = f.read_bytes()
    monkeypatch.setattr(sys, "argv", ["clean_staged.py", str(f)])
    assert clean_staged.main() == 0
    assert f.read_bytes() == before


def test_clean_hook_is_idempotent_for_an_image(tmp_path, monkeypatch):
    """Re-staging after a clean must be able to succeed.

    The hook exits 1 whenever it modified a file, so a file it reports as
    modified on every run can never be committed: the developer re-stages,
    the hook fires again, and nothing about the file has changed.
    """
    f = tmp_path / "pic.png"
    f.write_bytes(_minimal_png((b"tEXt", b"Software\x00Midjourney v6")))
    monkeypatch.setattr(sys, "argv", ["clean_staged.py", str(f)])
    assert clean_staged.main() == 1  # cleaned it, stop the commit for review
    cleaned = f.read_bytes()
    assert clean_staged.main() == 0  # nothing left to do, the commit proceeds
    assert f.read_bytes() == cleaned


def test_clean_hook_exits_0_for_an_already_clean_container(tmp_path, monkeypatch):
    f = tmp_path / "doc.md"
    f.write_text("# Title\n\nOrdinary prose.\n", encoding="utf-8")
    before = f.read_bytes()
    monkeypatch.setattr(sys, "argv", ["clean_staged.py", str(f)])
    assert clean_staged.main() == 0
    assert f.read_bytes() == before


# --- PDF: the operations run regardless, so judge the bytes ----------------

_PDF = (
    b"%PDF-1.4\n"
    b"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
    b"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
    b"3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 9 9]>>endobj\n"
    b"trailer<</Root 1 0 R/Size 4>>\n%%EOF\n"
)


@pytest.mark.skipif(
    shutil.which("exiftool") is None or shutil.which("qpdf") is None,
    reason="needs real exiftool and qpdf",
)
def test_pdf_clean_converges_and_then_reports_no_actions(tmp_path):
    """A second clean must produce identical bytes and no actions.

    qpdf regenerates the second half of the PDF /ID on every write unless it is
    asked not to, so cleaning the same file twice never produced the same bytes
    and the clean could never converge (#173).
    """
    src = tmp_path / "in.pdf"
    src.write_bytes(_PDF)
    first = tmp_path / "one.pdf"
    actions, _meta = clean_pdf(src, first)
    assert actions, "the first pass rewrites the document, which is a real change"

    second = tmp_path / "two.pdf"
    actions2, _meta2 = clean_pdf(first, second)
    assert second.read_bytes() == first.read_bytes(), "the clean must converge"
    assert actions2 == []


def test_pdf_without_a_cleaner_reports_no_actions_and_keeps_the_warning(tmp_path, monkeypatch):
    """Copying a PDF untouched is not an action, but the user must still hear it.

    The degraded-clean warning moved from `actions` (where it marked the file
    changed) to `meta["note"]`, which clean_file.py prints as a warning.
    """
    monkeypatch.setattr(container_meta, "which", lambda cmd: None)
    src = tmp_path / "in.pdf"
    src.write_bytes(_PDF)
    dest = tmp_path / "out.pdf"
    actions, meta = clean_pdf(src, dest)
    assert actions == []
    assert dest.read_bytes() == _PDF
    assert meta["degraded"] is True
    assert "no PDF cleaner available" in meta["note"]
