"""Non-regression coverage for the moov/udta offset-table corruption bug.

LOCAL PATCH (Circe, 2026-08-19). Background: wm-clean on an MP4 dropped
moov/udta (or a top-level uuid/jumb box) without correcting stco/co64 sample
offsets. Every faststart-optimized file (moov before mdat -- exactly how
video is packaged for web/social publishing) came out with every sample
offset pointing N bytes short of the real data: unplayable, while the
service still printed "OK pulito" because none of its checks ever decoded a
sample. Fixed in av_meta.py by remuxing through ffmpeg (which recomputes
offset tables from scratch) instead of hand-editing ISOBMFF boxes, plus a
decode-verification guard in clean_av() that refuses to write output and
raises instead of returning success if cleaning regresses a file from
decodable to non-decodable.

This file exercises the fix against real, ffmpeg-encoded media -- the
existing test_av_meta.py fixtures are hand-built byte structures with no
real trak/mdat content, which is exactly the class of input that can no
longer be meaningfully "cleaned" by a remux-based pipeline (there's nothing
for ffmpeg to remux). Real media is what actually proves the contract this
bug broke: metadata removed *and* still decodable.
"""

from __future__ import annotations

import shutil
import struct
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(SCRIPTS))

import pytest

from av_meta import clean_av, inspect_av
from container_meta import clean_container
from image_meta import clean_image

FFMPEG = shutil.which("ffmpeg")
FFPROBE = shutil.which("ffprobe")
requires_ffmpeg = pytest.mark.skipif(
    not (FFMPEG and FFPROBE), reason="ffmpeg/ffprobe not installed"
)

AI_COMMENT = "Generated by AI toolchain"


def _decodable(path: Path) -> bool:
    r = subprocess.run(
        [FFMPEG, "-v", "error", "-i", str(path), "-t", "3", "-f", "null", "-"],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    return r.returncode == 0


def _make_mp4(dest: Path, *, faststart: bool) -> None:
    cmd = [
        FFMPEG,
        "-y",
        "-v",
        "error",
        "-f",
        "lavfi",
        "-i",
        "testsrc=duration=1:size=64x64:rate=10",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-metadata",
        f"comment={AI_COMMENT}",
    ]
    if faststart:
        cmd += ["-movflags", "+faststart"]
    cmd.append(str(dest))
    subprocess.run(cmd, capture_output=True, text=True, timeout=60, check=True)


def _make_wav(dest: Path) -> None:
    subprocess.run(
        [
            FFMPEG,
            "-y",
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=1",
            "-metadata",
            f"comment={AI_COMMENT}",
            str(dest),
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=True,
    )


def _make_mp3(dest: Path) -> None:
    subprocess.run(
        [
            FFMPEG,
            "-y",
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:duration=1",
            "-c:a",
            "libmp3lame",
            "-metadata",
            f"comment={AI_COMMENT}",
            str(dest),
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=True,
    )


# ---------------------------------------------------------------------------
# The reported bug, reproduced exactly: faststart MP4 -> metadata gone, file
# still plays. Before the fix this raised no error and wrote a corrupt file.
# ---------------------------------------------------------------------------


@requires_ffmpeg
def test_mp4_faststart_cleaned_and_still_decodable(tmp_path):
    src = tmp_path / "faststart.mp4"
    _make_mp4(src, faststart=True)
    assert _decodable(src), "fixture itself must be valid media before testing the cleaner"

    before = inspect_av(src)
    assert before.has_ai_metadata is True

    dest = tmp_path / "faststart.clean.mp4"
    result = clean_av(src, dest, strip_all_metadata=True)

    assert result["still_has_ai_metadata"] is False
    assert AI_COMMENT.encode() not in dest.read_bytes()
    assert _decodable(dest), "regression: this is exactly the moov/udta offset-table bug"


@requires_ffmpeg
def test_mp4_non_faststart_cleaned_and_still_decodable(tmp_path):
    """The discriminant from the bug report: moov after mdat never corrupted
    even with the old code, because dropping udta didn't shift mdat. Kept as
    a control case -- must keep passing exactly like faststart now does."""
    src = tmp_path / "plain.mp4"
    _make_mp4(src, faststart=False)
    assert _decodable(src)

    dest = tmp_path / "plain.clean.mp4"
    result = clean_av(src, dest, strip_all_metadata=True)

    assert result["still_has_ai_metadata"] is False
    assert AI_COMMENT.encode() not in dest.read_bytes()
    assert _decodable(dest)


@requires_ffmpeg
def test_mp4_keep_non_ai_metadata_preserves_unflagged_tag_and_stays_decodable(tmp_path):
    """keep_non_ai_metadata mode must drop only the AI-hint tag, keep the
    rest, and still not corrupt the file -- the selective path (ffprobe ->
    -metadata key= on a single remux) is the trickiest one to get right."""
    src = tmp_path / "selective.mp4"
    cmd = [
        FFMPEG,
        "-y",
        "-v",
        "error",
        "-f",
        "lavfi",
        "-i",
        "testsrc=duration=1:size=64x64:rate=10",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-metadata",
        f"comment={AI_COMMENT}",
        "-metadata",
        "artist=Adobe Premiere Pro 2026",
        "-movflags",
        "+faststart",
        str(src),
    ]
    subprocess.run(cmd, capture_output=True, text=True, timeout=60, check=True)

    dest = tmp_path / "selective.clean.mp4"
    result = clean_av(src, dest, strip_all_metadata=False)

    out_bytes = dest.read_bytes()
    assert AI_COMMENT.encode() not in out_bytes
    assert b"Adobe Premiere Pro 2026" in out_bytes
    assert result["still_has_ai_metadata"] is False
    assert _decodable(dest)


@requires_ffmpeg
def test_wav_cleaned_and_still_decodable(tmp_path):
    src = tmp_path / "clip.wav"
    _make_wav(src)
    assert _decodable(src)

    before = inspect_av(src)
    assert before.has_ai_metadata is True

    dest = tmp_path / "clip.clean.wav"
    result = clean_av(src, dest, strip_all_metadata=True)

    assert result["still_has_ai_metadata"] is False
    assert AI_COMMENT.encode() not in dest.read_bytes()
    assert _decodable(dest)


@requires_ffmpeg
def test_mp3_cleaned_and_still_decodable(tmp_path):
    src = tmp_path / "clip.mp3"
    _make_mp3(src)
    assert _decodable(src)

    before = inspect_av(src)
    assert before.has_ai_metadata is True

    dest = tmp_path / "clip.clean.mp3"
    result = clean_av(src, dest, strip_all_metadata=True)

    assert result["still_has_ai_metadata"] is False
    assert AI_COMMENT.encode() not in dest.read_bytes()
    assert _decodable(dest)


# ---------------------------------------------------------------------------
# The anti-corruption guard itself: prove it actually blocks, not just that
# real media happens to clean successfully.
# ---------------------------------------------------------------------------


@requires_ffmpeg
def test_guard_blocks_and_leaves_original_untouched_when_cleaning_would_corrupt(
    tmp_path, monkeypatch
):
    """Simulate a remux that produces garbage (any future regression in the
    remux path would look like this) and confirm clean_av refuses to write
    dest and raises instead of returning "success"."""
    import av_meta

    src = tmp_path / "faststart.mp4"
    _make_mp4(src, faststart=True)

    def _broken_remux(data, **_kwargs):
        return b"not a real container" * 20, ["simulated corruption"]

    monkeypatch.setattr(av_meta, "_remux_mp4_ffmpeg", _broken_remux)

    dest = tmp_path / "should_not_exist.mp4"
    with pytest.raises(ValueError, match="integrity check"):
        av_meta.clean_av(src, dest, strip_all_metadata=True)

    assert not dest.exists()
    assert not dest.with_name(dest.name + ".verify-tmp").exists()
    # Original is a plain read -- clean_av never opens *src* for writing.
    assert _decodable(src)


# ---------------------------------------------------------------------------
# Unrelated pipelines must be unaffected -- this patch only touches
# av_meta.py / server.py's capabilities dict.
# ---------------------------------------------------------------------------


def _minimal_png_with_text_chunk(text: bytes) -> bytes:
    sig = b"\x89PNG\r\n\x1a\n"

    def chunk(tag: bytes, payload: bytes) -> bytes:
        import zlib

        return (
            struct.pack(">I", len(payload))
            + tag
            + payload
            + struct.pack(">I", zlib.crc32(tag + payload))
        )

    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0)
    idat_payload = bytes([0, 255, 0, 0])
    import zlib as _zlib

    idat = _zlib.compress(idat_payload)
    return (
        sig
        + chunk(b"IHDR", ihdr)
        + chunk(b"tEXt", b"Comment\x00" + text)
        + chunk(b"IDAT", idat)
        + chunk(b"IEND", b"")
    )


def test_png_cleaning_unaffected_by_this_patch(tmp_path):
    src = tmp_path / "tagged.png"
    src.write_bytes(_minimal_png_with_text_chunk(AI_COMMENT.encode()))
    dest = tmp_path / "tagged.clean.png"

    result = clean_image(src, dest, strip_all_metadata=True)

    assert AI_COMMENT.encode() not in dest.read_bytes()
    assert result["still_has_ai_metadata"] is False


def test_markdown_cleaning_unaffected_by_this_patch(tmp_path):
    src = tmp_path / "doc.md"
    src.write_text(f"# Title\n\n<!-- {AI_COMMENT} -->\nBody text.\n", encoding="utf-8")
    dest = tmp_path / "doc.clean.md"

    result = clean_container(src, dest, fmt="markdown")

    cleaned_text = dest.read_text(encoding="utf-8")
    assert "Body text." in cleaned_text
