"""An empty actions list means the cleaner left the bytes alone (#173).

Every strip_* used to append a "no X removed" filler when it removed nothing,
so the actions list was never empty for any non-text kind. clean_staged._changed()
reads that list to decide whether a file was modified, which made it
unconditionally True: the clean pre-commit hook exited 1 for every image and
container forever, and its "cleaned N file(s)" line carried no information.
"""

from __future__ import annotations

import struct
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "service" / "scripts"
sys.path.insert(0, str(SCRIPTS))

import clean_staged
from container_meta import clean_html, clean_markdown, clean_svg
from image_meta import strip_jpeg, strip_png


def _png_chunk(ctype: bytes, payload: bytes) -> bytes:
    crc = zlib.crc32(ctype + payload) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


def _minimal_png(*extra: tuple[bytes, bytes]) -> bytes:
    ihdr = struct.pack(">IIBBBBB", 1, 1, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", ihdr)
        + b"".join(_png_chunk(c, p) for c, p in extra)
        + _png_chunk(b"IDAT", zlib.compress(b"\x00\x00\x00\x00"))
        + _png_chunk(b"IEND", b"")
    )


def _minimal_jpeg(*, comment: bytes | None = None) -> bytes:
    out = b"\xff\xd8"
    if comment is not None:
        out += b"\xff\xfe" + struct.pack(">H", len(comment) + 2) + comment
    out += b"\xff\xda" + struct.pack(">H", 12) + b"\x01" * 10 + b"\xff\xd9"
    return out


# --- nothing removed -> no actions -----------------------------------------


def test_clean_png_reports_no_actions():
    data = _minimal_png()
    cleaned, actions = strip_png(data)
    assert cleaned == data
    assert actions == []


def test_clean_jpeg_reports_no_actions():
    data = _minimal_jpeg()
    cleaned, actions = strip_jpeg(data)
    assert cleaned == data
    assert actions == []


def test_clean_markdown_reports_no_actions():
    cleaned, actions = clean_markdown("# Title\n\nOrdinary prose.\n")
    assert actions == []
    assert "Ordinary prose." in cleaned


def test_clean_html_reports_no_actions():
    html = "<html><body><p>hello</p></body></html>"
    cleaned, actions = clean_html(html)
    assert actions == []
    assert cleaned == html


def test_clean_svg_reports_no_actions():
    data = b'<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>'
    cleaned, actions = clean_svg(data)
    assert actions == []
    assert cleaned == data


# --- a real removal still reports it ---------------------------------------


def test_png_with_ai_text_chunk_still_reports_the_drop():
    data = _minimal_png((b"tEXt", b"Software\x00Midjourney v6"))
    cleaned, actions = strip_png(data)
    assert actions, "a real removal must still produce an action"
    assert cleaned != data


def test_markdown_with_ai_frontmatter_still_reports_the_drop():
    cleaned, actions = clean_markdown("---\ngenerator: ChatGPT\n---\nBody\n")
    assert any("drop" in a for a in actions)
    assert "generator: ChatGPT" not in cleaned


def test_jpeg_preserved_scan_note_only_accompanies_a_removal():
    """The note describes what was carried over, not a change.

    On a no-op clean it must not appear, or it alone would mark the file
    changed. Alongside a real removal it is still worth reporting.
    """
    assert strip_jpeg(_minimal_jpeg())[1] == []
    marked = strip_jpeg(_minimal_jpeg(comment=b"Generated by ChatGPT"))[1]
    assert any("drop" in a for a in marked)
    assert any("preserved entropy-coded scan" in a for a in marked)


# --- the regression that motivated this ------------------------------------


def test_clean_hook_exits_0_for_an_already_clean_image(tmp_path, monkeypatch):
    f = tmp_path / "pic.png"
    f.write_bytes(_minimal_png())
    before = f.read_bytes()
    monkeypatch.setattr(sys, "argv", ["clean_staged.py", str(f)])
    assert clean_staged.main() == 0
    assert f.read_bytes() == before


def test_clean_hook_is_idempotent_for_an_image(tmp_path, monkeypatch):
    """Re-staging after a clean must be able to succeed.

    The hook exits 1 whenever it modified a file, so a file it reports as
    modified on every run can never be committed: the developer re-stages,
    the hook fires again, and nothing about the file has changed.
    """
    f = tmp_path / "pic.png"
    f.write_bytes(_minimal_png((b"tEXt", b"Software\x00Midjourney v6")))
    monkeypatch.setattr(sys, "argv", ["clean_staged.py", str(f)])
    assert clean_staged.main() == 1  # cleaned it, stop the commit for review
    cleaned = f.read_bytes()
    assert clean_staged.main() == 0  # nothing left to do, the commit proceeds
    assert f.read_bytes() == cleaned


def test_clean_hook_exits_0_for_an_already_clean_container(tmp_path, monkeypatch):
    f = tmp_path / "doc.md"
    f.write_text("# Title\n\nOrdinary prose.\n", encoding="utf-8")
    before = f.read_bytes()
    monkeypatch.setattr(sys, "argv", ["clean_staged.py", str(f)])
    assert clean_staged.main() == 0
    assert f.read_bytes() == before
